# CopyLeft 2026 github.com/sepiol026-wq | telegram:@samsepi0l_ovf. Licensed under AGPLv3.
[package]
name = "goygram_ext"
version = "0.7.72"
edition = "2021"
description = "Rust core for GoyGram"
license = "AGPL-3.0-only"
repository = "https://github.com/GoyGram/GoyGram"

[lib]
name = "goygram_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "abi3", "abi3-py311"] }
aes = "0.8.4"
aes-gcm = "0.10.3"
cipher = "0.4.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"

[profile.release]
strip = true
lto = true
opt-level = 3
